apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello
  template:
    metadata:
      labels:
        run: hello
    spec:
      containers:
      - image: dbenque/helloserver:v2
        imagePullPolicy: IfNotPresent
        name: hello
        env:
        - name: SLEEP
          value: 10
        ports:
        - containerPort: 80
          protocol: TCP